// <auto-generated />
namespace MyPhogGym.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Change_column_type_column_batDau_and_ketThuc_in_table_dichVu : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Change_column_type_column_batDau_and_ketThuc_in_table_dichVu));
        
        string IMigrationMetadata.Id
        {
            get { return "201812280941439_Change_column_type_column_batDau_and_ketThuc_in_table_dichVu"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
