// <auto-generated />
namespace MyPhogGym.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class change_table_khachHangDenTap_add_column_trangThai_soPhutConLai : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(change_table_khachHangDenTap_add_column_trangThai_soPhutConLai));
        
        string IMigrationMetadata.Id
        {
            get { return "201901101413332_change_table_khachHangDenTap_add_column_trangThai_soPhutConLai"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
